// app/splendor/fx/fxTypes.js

/**
 * FX Event Types
 * - Use these string constants to avoid typos across emitters/consumers.
 * - FXLayer.js currently switches on these names.
 *
 * Recommended usage:
 *   import { FX } from './fxTypes';
 *   fx.emit(FX.CARD_FLY_TO_PLAYER, { from:'board:t1:s2', to:'hud:ME', tier:1 });
 */

export const FX = Object.freeze({
  /** 1) Card reveal flip animation (slot reveal) */
  CARD_REVEAL_FLIP: 'CARD_REVEAL_FLIP',

  /** 2) Card sliding in from deck to board slot */
  CARD_SLIDE_IN: 'CARD_SLIDE_IN',

  /** 3) Selected/bought card flies to player area */
  CARD_FLY_TO_PLAYER: 'CARD_FLY_TO_PLAYER',

  /** 4) Gems burst/fly from bank (or reserve gold) to player HUD */
  GEM_BURST_TO_PLAYER: 'GEM_BURST_TO_PLAYER',

  /** 5) Noble claim ceremony overlay */
  NOBLE_CEREMONY: 'NOBLE_CEREMONY',

  /** 6) Turn transition wave / banner */
  TURN_WAVE: 'TURN_WAVE',

  /** 7) Card pick highlight (UI-level feedback) */
  CARD_PICK_HIGHLIGHT: 'CARD_PICK_HIGHLIGHT',

  /** 8) Buy fail shake / not-enough warning */
  BUY_FAIL_SHAKE: 'BUY_FAIL_SHAKE',

  /** 9) Score pop / floating text */
  SCORE_POP: 'SCORE_POP',

  /** 10) Victory overlay / confetti burst */
  VICTORY_BURST: 'VICTORY_BURST',
});

/**
 * Optional: tiny runtime validator (safe in dev, no-throw in prod)
 * Helps catch emitter typos quickly.
 */
export function isFxType(type) {
  if (!type) return false;
  // @ts-ignore
  return Object.prototype.hasOwnProperty.call(FX, Object.keys(FX).find((k) => FX[k] === type)) || Object.values(FX).includes(type);
}

/**
 * @typedef {Object} FxEvent
 * @property {string} id   Unique id (generated by FXProvider.emit)
 * @property {string} type One of FX.*
 * @property {number} ts   Timestamp (ms)
 * @property {any} [payload]
 * @property {any} [meta]
 */

/**
 * Convenience creator (if you ever want to build events before emitBatch)
 */
export function makeFxEvent(type, payload, meta) {
  return { type, payload, meta };
}
